### ISSUE TITLE
Better error when something is already listening on port

### ISSUE THREAD

**Issue by grabbou** [callstack/haul#207]
When there's e.g. another `packager` listening at another port, instead of printing an error:

```
INFO  Running haul start --platform all
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1265:14)
    at listen (net.js:1301:10)
    at Server.listen (net.js:1392:7)
    at Object.start [as action] (/Users/grabbou/Repositories/haul/src/commands/start.js:92:7)
    at run (/Users/grabbou/Repositories/haul/src/cliEntry.js:177:19)
```

either:
a) print a better / nicer error message
b) ask user what to do (exit / kill process and restart)

I am in favour of `b` which aligns well with our general idea of fixing mistakes.

**Comment by thymikee** [comment]
Why not try to automatically connect to another free port, like Browsersync does?

**Comment by satya164** [comment]
@thymikee the client would need to know to connect to the new port

**Comment by grabbou** [comment]
Yeah, if we change the port transparently, one will have to re run it's native client which I assume is not wanted behaviour

**Comment by thymikee** [comment]
Fair enough, thanks!

**Comment by Krizzu** [comment]
I'd like to work on this one, if no one took it already :)
