### ISSUE TITLE
Build failure with new @babel/ dependencies

### ISSUE THREAD

**Issue by Zephir77167** [callstack/haul#286]
### Current Behavior
Build failure when using new babel packages (`@babel/*`)

```
ERROR in ./index.ios.js
Module build failed: ReferenceError: Cannot read config file: /Users/adrien/Documents/GitHub/brigad-front-end/.eslintrc.js
Error: Unknown plugin "@babel/syntax-object-rest-spread" specified in "/Users/adrien/Documents/GitHub/brigad-front-end/.babelrc" at 0, attempted to resolve relative to "/Users/adrien/Documents/GitHub/brigad-front-end"
    at /Users/adrien/Documents/GitHub/brigad-front-end/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/adrien/Documents/GitHub/brigad-front-end/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/adrien/Documents/GitHub/brigad-front-end/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/adrien/Documents/GitHub/brigad-front-end/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/adrien/Documents/GitHub/brigad-front-end/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/adrien/Documents/GitHub/brigad-front-end/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/adrien/Documents/GitHub/brigad-front-end/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
 @ multi ./~/haul/src/utils/polyfillEnvironment.js ./index.ios.js
```

I have babel-core.0.0-bridge.0 installed (which fixed [this problem with babel-jest](https://github.com/facebook/jest/pull/4557)).

Maybe `babel-register` needs a bridge version as well. Not sure if this is the issue.

### Haul Configuration (webpack.haul.js)
```
const path = require('path');
const webpack = require('webpack');
const webpackResolve = require('./webpack.resolve');
const CircularDependencyPlugin = require('circular-dependency-plugin');

const eslintSettings = {
  extends: path.join(__dirname, '.eslintrc.js'),
  configFile: path.join(__dirname, '.eslintrc.js'),
  emitWarning: true,
  cache: false,
};

const babelSettings = {
  extends: path.join(__dirname, '.babelrc'),
};

const NODE_ENV = process.env.NODE_ENV === 'production' ? 'production' : 'development';
const STAGE = process.env.STAGE || 'development';

let envConfig;
try {
  // eslint-disable-next-line import/no-dynamic-require, global-require
  envConfig = require(`./.env.${STAGE}.json`);
} catch (e) {
  envConfig = {};
}

module.exports = ({ platform } = {}, defaults = {}) => ({
  ...defaults,
  devtool: 'cheap-module-source-map',
  resolve: {
    ...defaults.resolve,
    ...webpackResolve,
  },
  resolveLoader: {
    ...defaults.resolve,
    ...webpackResolve,
  },
  output: {
    filename: `index.${platform}.bundle`,
  },
  module: {
    ...defaults.module,
    rules: [
      ...(defaults.module ? defaults.module.rules : []),
      {
        enforce: 'pre',
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'eslint-loader',
        options: eslintSettings,
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: babelSettings,
      },
    ],
  },
  entry: `./index.${platform}.js`,
  plugins: [
    ...defaults.plugins,
    new webpack.SourceMapDevToolPlugin({
      test: [/\.js$/, /\.jsbundle$/],
      filename: '[file].map',
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(NODE_ENV),
        BRIGAD_STAGE: JSON.stringify(BRIGAD_STAGE),
      },
    }),
    new CircularDependencyPlugin({
      // exclude detection of files based on a RegExp
      exclude: /a\.js|node_modules/,
      // add errors to webpack instead of warnings
      failOnError: true,
    }),
  ],
});
```

webpack.resolve.js:

```
const path = require('path');

module.exports = {
  alias: {
    src: path.resolve(__dirname, 'src'),
    assets: path.resolve(__dirname, 'assets'),
  },
  modules: [
    'node_modules',
    'src',
    'assets',
    path.join(__dirname, '../../node_modules'),
    path.join(__dirname, 'node_modules'),
  ],
};
```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-beta.6
| react-native     |  0.49.3
| node             | 8.9.1
| npm or yarn      | Yarn 1.3.2

**Comment by Zephir77167** [comment]
Update: https://github.com/babel/babel/blob/master/packages/babel-register/package.json version `7.0.0-beta.32` of `babel-register` seems to rely on `@babel/core`. Bumping the version would solve my problem, but I don't know what other implications it would have.

**Comment by satya164** [comment]
React Native's Babel preset still uses Babel 6, so I don't think we can update babel plugins.

**Comment by jukben** [comment]
I agree with @satya164. We could discuss it again when it will be out of beta. Could you please fallback to `babel-xxx` (6.x) version?

**Comment by Zephir77167** [comment]
I will do this for the moment and wait for everyone to upgrade to Babel 7. Thanks for the quick replies!
