### ISSUE TITLE
RN 0.50.4 Android crashes simply after reloading the app

### ISSUE THREAD

**Issue by Ble3k** [callstack/haul#305]
Hi! First of all want to say thank you for this good project, it makes react-native developer's life much easier. If it will be necessary to provide more info, tell exactly what do you need, and I will try to provide it.

### Current Behavior
1) Starting emulator NEXUS_5X_API_26_x86
2) Starting haul for android (haul-start --platform android)
3) Starting react-native (react-native run-android)

Currently when I try to reload (cmd + m -> reload) the app is crashing every now and then.
Then when I try to open my app from menu, it's behavior is the same every now and then.

### Expected Behavior
I expected my app not to crash after reloading.

### Haul Configuration (webpack.haul.js)
```javascript
const path = require('path')

module.exports = ({ platform }, defaults) => ({
  entry: './index.js',
  module: {
    ...defaults.module,
  },
  resolve: {
    ...defaults.resolve,
    modules: [path.resolve(__dirname, 'src'), 'node_modules'],
  },
})
```

### Your Environment
| software   - OSX
| version - 10.13 High Sierra 
| Haul -  ^1.0.0-beta.10
| react-native - 0.50.4
| node - 8.9.1
| npm - 5.5.1

P.S. I made a short video for you guys, hope someone can help me. Will appreciate much!
http://www.giphy.com/gifs/3osBLzh4Yo4sNxVBWU

**Comment by Krizzu** [comment]
Hey @Ble3k!
Do you get any error when app crashes? If not, have you checked android logs? (using either `react-native log-android` or `adb logcat`)

**Comment by Ble3k** [comment]
Thank you for your replay, I will provide some logs soon.

**Comment by Krizzu** [comment]
@Ble3k Hey!
I see what's happening - something is not right when requesting a bundle (see 304 on the bottom console). 
To confirm this, can you send a GET request to `index.android.bundle?platform=android`, using tool like postman? Can You tell me what you get as response?
Also, can you tell me a bit about how you start your `Android emulator`? 

Thanks!

**Comment by Ble3k** [comment]
@Krizzu, I have made some logs, so here it is:

1) From react-native log-android
```
Starting the logger (/Users/RFateev/Library/Android/sdk/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V)...
--------- beginning of main
--------- beginning of system
11-29 06:58:10.797  2976  2976 D ReactNative: ReactInstanceManager.ctor()
11-29 06:58:10.946  2976  2976 D ReactNative: ReactInstanceManager.createReactContextInBackground()
11-29 06:58:10.946  2976  2976 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
11-29 06:58:11.410  2976  2976 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()
11-29 06:58:11.410  2976  2976 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
11-29 06:58:11.410  2976  2976 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
11-29 06:58:12.260  2976  3018 D ReactNative: ReactInstanceManager.createReactContext()
11-29 06:58:12.396  2976  3018 D ReactNative: Initializing React Xplat Bridge.
11-29 06:58:12.409  2976  3018 D ReactNative: Initializing React Xplat Bridge before initializeBridge
11-29 06:58:12.414  2976  3018 D ReactNative: Initializing React Xplat Bridge after initializeBridge
11-29 06:58:12.414  2976  3018 D ReactNative: CatalystInstanceImpl.runJSBundle()
11-29 06:58:12.421  2976  3031 D ReactNative: ReactInstanceManager.setupReactContext()
11-29 06:58:12.421  2976  3031 D ReactNative: CatalystInstanceImpl.initialize()
11-29 06:58:12.422  2976  3031 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
GET /index.android.bundle 200 6304993 - 11.846 ms
GET /index.android.bundle 200 6304993 - 16.142 ms
GET /index.android.bundle 200 6304993 - 14.741 ms
11-29 07:02:31.795  2976  2976 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()
11-29 07:02:31.795  2976  2976 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
11-29 07:02:31.795  2976  2976 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
11-29 07:02:31.795  2976  2976 D ReactNative: ReactInstanceManager.tearDownReactContext()
11-29 07:02:31.800  2976  2976 D ReactNative: CatalystInstanceImpl.destroy() start
11-29 07:02:31.936  2976  3029 D ReactNative: CatalystInstanceImpl.destroy() end
11-29 07:02:31.972  2976  3199 D ReactNative: ReactInstanceManager.createReactContext()
11-29 07:02:32.116  2976  3199 D ReactNative: Initializing React Xplat Bridge.
11-29 07:02:32.143  2976  3199 D ReactNative: Initializing React Xplat Bridge before initializeBridge
11-29 07:02:32.147  2976  3199 D ReactNative: Initializing React Xplat Bridge after initializeBridge
11-29 07:02:32.147  2976  3199 D ReactNative: CatalystInstanceImpl.runJSBundle()
11-29 07:02:32.169  2976  3207 D ReactNative: ReactInstanceManager.setupReactContext()
11-29 07:02:32.169  2976  3207 D ReactNative: CatalystInstanceImpl.initialize()
11-29 07:02:32.171  2976  3207 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
GET /index.android.bundle 304 undefined - 14.168 ms
--------- beginning of crash
```

So there is 200 OK when app is starting, then I reload, get 304 undefined and app is crashing.

2) GET request to ```index.android.bundle?platform=android``` returns me:
  - STATUS 200 OK
  - Thousands strings of bundled code

Do you need all this code ?
http://joxi.ru/brRKMBOfQRGaDm

3) To run my emulator i use this command 
  - ```emulator -netdelay none -netspeed full -avd Nexus_5X_API_26_x86```

Where emulator is GLOBAL system variable. Part of my .bash_profile
```
...
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
...
```

**Comment by Krizzu** [comment]
@Ble3k Thanks for exhaustive report!

For me, it has something to do with Android emu. You can clearly get bundle using postman (You get code 200), but on Android, you never reach Haul. (I guess)

Is this a fresh project? Any steps to reproduce it? I just tried with the latest RN and Haul, everything went smoothly.
Have you changed any settings in Haul/Emulator?

**Comment by Ble3k** [comment]
1) Yes, this is fresh project, but this command for emulator was written three/four months ago, in last project. Then I have just created new project, but didn't reinstall any dependencies for android to run with react-native, so emulator's settings are the same as in last project. The last project emulator settings was set up by reading this http://facebook.github.io/react-native/releases/0.42/docs/getting-started.html. Now I see that in 0.50 version nothing changed for the emulator. Can you tell me, how do you launch the emulator ?

2) I haven't changed any settings in Haul/Emulator.

**Comment by Krizzu** [comment]
Normally I do it the same way as you (have shell script for easy picking different emu versions) or by launching it from Android studio.

Can you run `adb reverse tcp:8081 tcp:8081` successfully? Have you got the possibility to check it on a real device? Or different emu? (Create another one from Android Studio AVD, with maybe different API?)
What about iOS? Does the issue still persist?

**Comment by Ble3k** [comment]
Unfortunately I can't run it on a real device. But I will try on different emu.

On iOS all works perfectly.
Thank you for your help. I will write something about running on different device soon.

**Comment by Ble3k** [comment]
@Krizzu, I have made some more useful logs from android studio.
Also I should say that I run ```adb reverse tcp:8081 tcp:8081``` successfully.
1) I opened Nexus emu as usual, press cmd + d to open dev menu
2) Clear all log data
3) Press reload
4) Got logs (maybe 'FATAL' section will tell us something)
```
11-29 10:29:46.132 3154-3177/com.binomysteryshopper D/EGL_emulation: eglMakeCurrent: 0xee3e4a20: ver 2 0 (tinfo 0xee3d26c0)
11-29 10:29:50.349 3154-3154/com.binomysteryshopper D/ReactNative: ReactInstanceManager.onReloadWithJSDebugger()
11-29 10:29:50.349 3154-3154/com.binomysteryshopper D/ReactNative: ReactInstanceManager.recreateReactContextInBackground()
11-29 10:29:50.349 3154-3154/com.binomysteryshopper D/ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
11-29 10:29:50.349 3154-3154/com.binomysteryshopper D/ReactNative: ReactInstanceManager.tearDownReactContext()
11-29 10:29:50.355 3154-3154/com.binomysteryshopper D/ReactNative: CatalystInstanceImpl.destroy() start
11-29 10:29:50.357 3154-3154/com.binomysteryshopper W/unknown:ReactNative: Packager connection already open, nooping.
11-29 10:29:50.378 3154-3177/com.binomysteryshopper D/EGL_emulation: eglMakeCurrent: 0xee3e4a20: ver 2 0 (tinfo 0xee3d26c0)
11-29 10:29:50.383 3154-3177/com.binomysteryshopper E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeaa4b220
11-29 10:29:50.400 3154-3177/com.binomysteryshopper D/EGL_emulation: eglMakeCurrent: 0xee3e4a20: ver 2 0 (tinfo 0xee3d26c0)
11-29 10:29:50.401 3154-3278/com.binomysteryshopper W/unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["websocketFailed",{"message":null,"id":0}])
                                                                           
                                                                           --------- beginning of system
11-29 10:29:50.431 1602-2173/system_process W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@81859c3 attribute=null, token = android.os.BinderProxy@c411168
11-29 10:29:50.479 3154-3286/com.binomysteryshopper D/ReactNative: ReactInstanceManager.createReactContext()
11-29 10:29:50.481 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
11-29 10:29:50.484 3154-3177/com.binomysteryshopper D/EGL_emulation: eglMakeCurrent: 0xee3e4a20: ver 2 0 (tinfo 0xee3d26c0)
11-29 10:29:50.486 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
11-29 10:29:50.499 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
11-29 10:29:50.514 3154-3177/com.binomysteryshopper D/EGL_emulation: eglMakeCurrent: 0xee3e4a20: ver 2 0 (tinfo 0xee3d26c0)
11-29 10:29:50.521 3154-3177/com.binomysteryshopper E/Surface: getSlotFromBufferLocked: unknown buffer: 0xeaa4b0e0
11-29 10:29:50.523 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
11-29 10:29:50.535 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
11-29 10:29:50.536 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
11-29 10:29:50.537 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
11-29 10:29:50.538 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
11-29 10:29:50.543 1263-1314/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 299008
11-29 10:29:50.565 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
                                                                                          
                                                                                          [ 11-29 10:29:50.570  3154: 3154 D/         ]
                                                                                          HostConnection::get() New Host Connection established 0xdeea2e80, tid 3154
11-29 10:29:50.572 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
11-29 10:29:50.573 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
11-29 10:29:50.574 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
11-29 10:29:50.614 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
11-29 10:29:50.615 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
11-29 10:29:50.615 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
11-29 10:29:50.616 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
11-29 10:29:50.634 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
11-29 10:29:50.634 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
11-29 10:29:50.635 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
11-29 10:29:50.635 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
11-29 10:29:50.642 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
11-29 10:29:50.643 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
11-29 10:29:50.644 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
11-29 10:29:50.647 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
11-29 10:29:50.648 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
11-29 10:29:50.648 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
11-29 10:29:50.648 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
11-29 10:29:50.649 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
11-29 10:29:50.650 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
11-29 10:29:50.650 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
11-29 10:29:50.651 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
11-29 10:29:50.651 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
11-29 10:29:50.652 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
11-29 10:29:50.693 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
11-29 10:29:50.695 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
11-29 10:29:50.697 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
11-29 10:29:50.698 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
11-29 10:29:50.708 1602-1621/system_process W/AppOps: Finishing op nesting under-run: uid 10064 pkg com.binomysteryshopper code 24 time=0 duration=0 nesting=0
11-29 10:29:50.717 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
11-29 10:29:50.722 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
11-29 10:29:50.723 3154-3286/com.binomysteryshopper W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
11-29 10:29:50.724 3154-3286/com.binomysteryshopper D/ReactNative: Initializing React Xplat Bridge.
11-29 10:29:50.732 3154-3286/com.binomysteryshopper D/ReactNative: Initializing React Xplat Bridge before initializeBridge
11-29 10:29:50.733 3154-3286/com.binomysteryshopper D/ReactNative: Initializing React Xplat Bridge after initializeBridge
11-29 10:29:50.734 3154-3286/com.binomysteryshopper D/ReactNative: CatalystInstanceImpl.runJSBundle()
11-29 10:29:50.741 3154-3291/com.binomysteryshopper D/ReactNative: ReactInstanceManager.setupReactContext()
11-29 10:29:50.741 3154-3291/com.binomysteryshopper D/ReactNative: CatalystInstanceImpl.initialize()
11-29 10:29:50.742 3154-3291/com.binomysteryshopper W/unknown:ReactNative: Packager connection already open, nooping.
11-29 10:29:50.743 3154-3291/com.binomysteryshopper D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
                                                                   
                                                                   [ 11-29 10:29:50.743  3154: 3154 W/         ]
                                                                   Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
                                                                   
                                                                   --------- beginning of crash
11-29 10:29:50.753 3154-3154/com.binomysteryshopper A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xe1b30000 in tid 3154 (omysteryshopper)
11-29 10:29:50.861 1323-1323/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-29 10:29:50.861 1323-1323/? A/DEBUG: Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:6.0/MASTER/4174734:userdebug/test-keys'
11-29 10:29:50.861 1323-1323/? A/DEBUG: Revision: '0'
11-29 10:29:50.862 1323-1323/? A/DEBUG: ABI: 'x86'
11-29 10:29:50.862 1323-1323/? A/DEBUG: pid: 3154, tid: 3154, name: omysteryshopper  >>> com.binomysteryshopper <<<
11-29 10:29:50.862 1323-1323/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xe1b30000
11-29 10:29:50.879 1323-1323/? A/DEBUG:     eax 00048c60  ebx eab5aeb4  ecx 00010318  edx f403d6bc
11-29 10:29:50.880 1323-1323/? A/DEBUG:     esi de5ba000  edi e1b30000
11-29 10:29:50.880 1323-1323/? A/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000007  xss 0000002b
11-29 10:29:50.881 1323-1323/? A/DEBUG:     eip eab54a38  ebp 003fffc4  esp ffdc2994  flags 00210206
11-29 10:29:50.887 1323-1323/? A/DEBUG: backtrace:
11-29 10:29:50.888 1323-1323/? A/DEBUG:     #00 pc 00002a38  /system/lib/libOpenglSystemCommon.so (goldfish_dma_write(goldfish_dma_context*, void*, unsigned int)+56)
11-29 10:29:50.888 1323-1323/? A/DEBUG:     #01 pc 00003853  /system/lib/libOpenglSystemCommon.so (ExtendedRCEncoderContext::lockAndWriteDma(void*, unsigned int)+67)
11-29 10:29:50.888 1323-1323/? A/DEBUG:     #02 pc 00003062  /system/lib/lib_renderControl_enc.so
11-29 10:29:50.888 1323-1323/? A/DEBUG:     #03 pc 0000314e  /system/lib/hw/gralloc.ranchu.so
11-29 10:29:50.888 1323-1323/? A/DEBUG:     #04 pc 0000a351  /system/lib/libui.so (android::GraphicBufferMapper::unlockAsync(native_handle const*, int*)+113)
11-29 10:29:50.888 1323-1323/? A/DEBUG:     #05 pc 000086f1  /system/lib/libui.so (android::GraphicBuffer::unlockAsync(int*)+49)
11-29 10:29:50.889 1323-1323/? A/DEBUG:     #06 pc 0006bae6  /system/lib/libgui.so (android::Surface::unlockAndPost()+70)
11-29 10:29:50.889 1323-1323/? A/DEBUG:     #07 pc 000b6b00  /system/lib/libandroid_runtime.so
11-29 10:29:50.889 1323-1323/? A/DEBUG:     #08 pc 728e5746  /data/dalvik-cache/x86/system@framework@boot.oat (offset 0x1eb2000)
11-29 10:29:51.163 1323-1323/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_09
11-29 10:29:51.163 1323-1323/? E/DEBUG: AM write failed: Broken pipe
11-29 10:29:51.163 1602-1619/system_process I/BootReceiver: Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
11-29 10:29:51.167 1602-3297/system_process W/ActivityManager:   Force finishing activity com.binomysteryshopper/.MainActivity
11-29 10:29:51.199 1263-1280/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1019904
                                                 
                                                 
                                                 [ 11-29 10:29:51.219  1602: 3297 D/         ]
                                                 HostConnection::get() New Host Connection established 0x7f52cbc3c000, tid 3297
11-29 10:29:51.269 1602-1645/system_process W/InputDispatcher: channel '9724981 com.binomysteryshopper/com.binomysteryshopper.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-29 10:29:51.269 1602-1645/system_process E/InputDispatcher: channel '9724981 com.binomysteryshopper/com.binomysteryshopper.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-29 10:29:51.278 1602-1613/system_process D/GraphicsStats: Buffer count: 3
11-29 10:29:51.280 1602-1645/system_process W/InputDispatcher: channel '641172  (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-29 10:29:51.280 1602-1645/system_process E/InputDispatcher: channel '641172  (server)' ~ Channel is unrecoverably broken and will be disposed!
11-29 10:29:51.284 1332-1332/? I/Zygote: Process 3154 exited due to signal (11)
                                         
                                         [ 11-29 10:29:51.361  1602: 3297 W/         ]
                                         Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
11-29 10:29:51.364 1263-1263/? E/EGL_emulation: tid 1263: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
11-29 10:29:51.373 1602-1956/system_process I/WindowState: WIN DEATH: Window{641172 u0 com.binomysteryshopper}
11-29 10:29:51.373 1602-1956/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '641172  (server)'
11-29 10:29:51.384 1602-1956/system_process W/AppOps: Finishing op nesting under-run: uid 10064 pkg com.binomysteryshopper code 24 time=0 duration=0 nesting=0
11-29 10:29:51.404 1602-2027/system_process I/WindowState: WIN DEATH: Window{9724981 u0 com.binomysteryshopper/com.binomysteryshopper.MainActivity}
11-29 10:29:51.404 1602-2027/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '9724981 com.binomysteryshopper/com.binomysteryshopper.MainActivity (server)'
11-29 10:29:51.409 1602-3297/system_process W/ActivityManager: Exception thrown during pause
                                                               android.os.DeadObjectException
                                                                   at android.os.BinderProxy.transactNative(Native Method)
                                                                   at android.os.BinderProxy.transact(Binder.java:503)
                                                                   at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
                                                                   at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
                                                                   at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
                                                                   at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
                                                                   at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
                                                                   at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
                                                                   at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
                                                                   at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
                                                                   at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
                                                                   at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
11-29 10:29:51.413 1602-1602/system_process W/art: Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 187ms
11-29 10:29:51.415 1248-1248/? E/lowmemorykiller: Error opening /proc/3154/oom_score_adj; errno=2
11-29 10:29:51.429 1602-1747/system_process I/ActivityManager: Process com.binomysteryshopper (pid 3154) has died
11-29 10:29:51.488 1602-1612/system_process I/art: Background partial concurrent mark sweep GC freed 20680(1471KB) AllocSpace objects, 17(1864KB) LOS objects, 30% free, 9MB/13MB, paused 3.004ms total 108.436ms
11-29 10:29:51.561 1602-3118/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
11-29 10:29:51.567 1602-3118/system_process D/EGL_emulation: eglCreateContext: 0x7f52cbccc1e0: maj 2 min 0 rcv 2
11-29 10:29:51.569 1602-3118/system_process D/EGL_emulation: eglMakeCurrent: 0x7f52cbccc1e0: ver 2 0 (tinfo 0x7f52cc7a5880)
11-29 10:29:51.596 1602-3118/system_process D/EGL_emulation: eglMakeCurrent: 0x7f52cbccc1e0: ver 2 0 (tinfo 0x7f52cc7a5880)
11-29 10:29:51.677 1988-2188/com.android.launcher3 D/EGL_emulation: eglMakeCurrent: 0x7f52deab54a0: ver 2 0 (tinfo 0x7f52d347f1a0)
11-29 10:29:51.866 1602-1959/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-29 10:29:51.898 1602-2161/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-29 10:29:52.212 1602-1621/system_process W/WindowAnimator: Failed to dispatch window animation state change.
                                                              android.os.DeadObjectException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                  at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                                  at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                                  at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                                  at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                                  at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
11-29 10:29:53.482 1327-1632/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 1806525 , only wrote 1669686
11-29 10:30:41.641 1263-1294/? D/hwcomposer: hw_composer sent 1263 syncs in 75s
11-29 10:31:41.918 1263-1294/? D/hwcomposer: hw_composer sent 8 syncs in 60s

```
----------------------------------------------------------------------------------------------------

Now I'm trying to use another emulator, with same API level (because react-native tell us to use exactly 23 lvl Marshmallow) and it works. Trying to reload tons of times and it doesn't crash)))

So if someone will face this problem:
- Emulator that I used when app was crashing - Nexus 5X
- Emulator that I use now when app isn't crashing - Pixel

P.S. Maybe somebody will solve the problem with Nexus and logs above will be helpful.

**Comment by Krizzu** [comment]
@Ble3k 
I had the same issue with other emulator (dunno which model), with networking. Could not get it online or connect to my local machine. Haven't fixed it, just switched to different one.

And I assume that different emulator solved it for you?

**Comment by Ble3k** [comment]
Yes, new emulator solved my issue.
