### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by gastonmorixe** [callstack/haul#384]
```
 ERROR  Failed to compile.

./index.js
Module build failed: Thread Loader (Worker 0)
/Users/work1/Projects/LEMON/Lemon/index.js: Cannot read property 'find' of undefined

   at getReturnedId (/Users/work1/Projects/LEMON/Lemon/node_modules/haul/src/hot/babelPlugin.js:65:37)
   at Object.CallExpression (/Users/work1/Projects/LEMON/Lemon/node_modules/haul/src/hot/babelPlugin.js:99:26)
   at NodePath._call (/Users/work1/Projects/LEMON/Lemon/node_modules/babel-traverse/lib/path/context.js:76:18)
   at NodePath.call (/Users/work1/Projects/LEMON/Lemon/node_modules/babel-traverse/lib/path/context.js:48:17)
   at NodePath.visit (/Users/work1/Projects/LEMON/Lemon/node_modules/babel-traverse/lib/path/context.js:105:12)
   at TraversalContext.visitQueue (/Users/work1/Projects/LEMON/Lemon/node_modules/babel-traverse/lib/context.js:150:16)
   at TraversalContext.visitSingle (/Users/work1/Projects/LEMON/Lemon/node_modules/babel-traverse/lib/context.js:108:19)
   at TraversalContext.visit (/Users/work1/Projects/LEMON/Lemon/node_modules/babel-traverse/lib/context.js:192:19)
   at Function.traverse.node (/Users/work1/Projects/LEMON/Lemon/node_modules/babel-traverse/lib/index.js:114:17)
   at NodePath.visit (/Users/work1/Projects/LEMON/Lemon/node_modules/babel-traverse/lib/path/context.js:115:19)
@ ./index.ios.js 1:0-21
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./index.ios.js
GET /index.ios.bundle 200 6815491 - 4542.397 ms
GET /index.ios.bundle 200 6815491 - 9.383 ms
GET /index.ios.bundle 200 6815491 - 10.703 ms
GET /index.ios.bundle 200 6815491 - 11.286 ms
GET /index.ios.bundle 200 6815491 - 12.633 ms
GET /index.ios.bundle 200 6815491 - 10.598 ms
GET /index.ios.bundle 200 6815491 - 10.740 ms
GET /index.ios.bundle 200 6815491 - 10.968 ms
GET /index.ios.bundle 200 6815491 - 11.548 ms
GET /index.ios.bundle 200 6815491 - 13.369 ms

```

**Comment by satya164** [comment]
Can you post a repro? It's not really possible to know what's happening without a repro.

**Comment by gastonmorixe** [comment]
Sorry :/ don’t have time. Just gave up and went back to metro. It happens when adding the auto way for config HMR. Otherwise it works ok. 

Still I couldn’t make  symlinks neither so. Had to rollback. 

Thanks 

Best,

Gaston 
L
