### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'afterCompile' of undefined

### ISSUE THREAD

**Issue by Kottidev** [callstack/haul#386]
### Current Behavior

```
 ERROR  Failed to compile.

./src/index.tsx
Module build failed: TypeError: Cannot read property 'afterCompile' of undefined
   at successfulTypeScriptInstance (/Users/anouar/Documents/myjobs/misk/node_modules/ts-loader/dist/instances.js:147:28)
   at Object.getTypeScriptInstance (/Users/anouar/Documents/myjobs/misk/node_modules/ts-loader/dist/instances.js:48:12)
   at Object.loader (/Users/anouar/Documents/myjobs/misk/node_modules/ts-loader/dist/index.js:16:41)
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./src/index.tsx


```
### Expected Behavior

it's an error with ts-loader ?
https://github.com/TypeStrong/ts-loader/issues/729

### Haul Configuration (webpack.haul.js)

```

module.exports = ({ platform }, { module, resolve }) => ({
  entry: "./src/index.tsx",
  module: {
    ...module,
    rules: [
      {
        exclude: "/node_modules/",
        test: /\.(ts|tsx)$/,
        use: [
          {
            loader: "babel-loader"
          },
          {
            loader: "ts-loader"
          }
        ]
      },
      ...module.rules
    ]
  },
  resolve: {
    ...resolve,
    extensions: [
      ".ts",
      ".tsx",
      `.${platform}.ts`,
      ".native.ts",
      `.${platform}.tsx`,
      ".native.tsx",
      ...resolve.extensions
    ]
  }
});

```

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |   1.0.0-beta.13 
| react-native     |   0.54.0 
| node             | v8.10.0
| yarn      | 1.3.2

**Comment by Krizzu** [comment]
Hi @Kottidev 
Looks like this error occurs if you try to use this loader with webpack version other than 4.

We haven't released Haul with webpack 4 yet, so please try to use ts-loader version 3.5.0.

**Comment by Anu1601CS** [comment]
@Kottidev Thanks You save my life. It works for me :)
