### ISSUE TITLE
Ctrl-C throws EINVAL on unlink in Fork.terminate().

### ISSUE THREAD

**Issue by simonbuchan** [callstack/haul#421]
### Current Behavior

`> yarn haul` then reload app - haul gives a compile error ("Can't resolve './src', since I haven't configured anything yet). Ctrl-C then I get the error output:

```
fs.js:1085
  return binding.unlink(pathModule.toNamespacedPath(path));
                 ^

Error: EINVAL: invalid argument, unlink '//./pipe/tmp/HAUL_SOCKET_120489_.socket'
    at Object.fs.unlinkSync (fs.js:1085:18)
    at Fork.terminate (C:/code/skilitics/hub/mobile/node_modules/haul/src/compiler/Fork.js:116:12)
    at Object.keys.forEach.platform (C:/code/skilitics/hub/mobile/node_modules/haul/src/compiler/Compiler.js:155:28)
    at Array.forEach (<anonymous>)
    at Compiler.terminate (C:/code/skilitics/hub/mobile/node_modules/haul/src/compiler/Compiler.js:154:29)
    at process.on.err (C:/code/skilitics/hub/mobile/node_modules/haul/src/server/index.js:57:14)
    at process.emit (events.js:132:15)
    at process._fatalException (bootstrap_node.js:434:26)
```

### Expected Behavior
Exits cleanly/silently (well as cleanly as yarn run does on windows, at least - it always asks `Terminate batch job (Y/N)`)

### Haul Configuration (webpack.haul.js)
No config file (yet), using default. No main / browser fields 

### Your Environment
Windows 10 April 2018 Update

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.0
| react-native     |  0.55.2
| node             | 9.6.1
| npm or yarn      | yarn 1.6.0

**Comment by zamotany** [comment]
Have you tried running it in [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)??

**Comment by simonbuchan** [comment]
Seems to work fine there. If I simply add `process.platform !== 'win32' &&` to [the check](https://github.com/callstack/haul/blob/849494b0e579866aef39a686f36a71cb71068592/src/compiler/Fork.js#L115) , it seems to fix it, but I'd like to give it a bit more testing before doing a PR (also, it's a pain to manage separate open PRs and still use the fixes locally 😉)

**Comment by zamotany** [comment]
Closing due to inactivity. If anyone have an similar problem, please open a separate issue and make sure you're using `@haul-bundler/cli`
