### ISSUE TITLE
Android crash with bundle deltas enabled

### ISSUE THREAD

**Issue by tido64** [callstack/haul#515]
### Current Behavior

Our Android app crashes on startup if dev support is enabled:

```
2019-01-28 22:36:50.040 7143-7201/com.mycompany.demo E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.mycompany.demo, PID: 7143
    java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT
        at android.util.JsonReader.nextString(JsonReader.java:408)
        at com.facebook.react.devsupport.BundleDeltaClient$BundleDeltaJavaClient.patchDelta(BundleDeltaClient.java:162)
        at com.facebook.react.devsupport.BundleDeltaClient$BundleDeltaJavaClient.processDelta(BundleDeltaClient.java:108)
        at com.facebook.react.devsupport.BundleDeltaClient.processDelta(BundleDeltaClient.java:71)
        at com.facebook.react.devsupport.BundleDownloader.processBundleResult(BundleDownloader.java:314)
        at com.facebook.react.devsupport.BundleDownloader.access$200(BundleDownloader.java:37)
        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:174)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

### Expected Behavior

It shouldn't crash 😄 

### Your Environment

| software         | version
| ---------------- | -------
| Haul             |  1.0.0-rc.10 (62a1a76e74) |
| react-native     |  0.57.0 |
| node             | 8.15.0 |
| yarn      | 1.13.0 |

### Workaround

We're able to workaround this issue by disabling it in code:

```java
DevInternalSettings internalSettings = DevInternalSettings.withoutNativeDeltaClient(this, null);
internalSettings.setBundleDeltasEnabled(false);
```

**Comment by jwaldrip** [comment]
@tido64 where did you put that workaround? can you provide a more complete example?

**Comment by tido64** [comment]
@jwaldrip In your app, before you create a `ReactNativeHost`. I don't think you can disable it in Haul.

**Comment by jwaldrip** [comment]
@tido64 my java is rusty. Can you show me what the MainApplication.java looks like?

**Comment by tido64** [comment]
@jwaldrip Here's a [demo app](https://github.com/petterh/react-europe-demo) a colleague of mine wrote. I would put the two lines [before line 50](https://github.com/petterh/react-europe-demo/blob/master/DemoApp/app/src/main/java/com/contoso/demoapp/ReactDemoActivity.java#L50). Line 50 will eventually [call `ReactInstanceManager.builder()`](https://github.com/petterh/react-europe-demo/blob/master/DemoApp/reactnativedemolibrary/src/main/java/com/contoso/reactnativedemolibrary/ReactNativeDemoLibrary.java#L86). You can add the two lines anywhere before you call `ReactInstanceManager.builder()`. You just need to make sure that `this` is an instance of `android.content.Context` (and an `Activity` inherits one).

**Comment by Summys** [comment]
I'm using react-native-navigation and I couldn't manage to add those two lines anywhere in my code, so I found a more trivial approach.
1. Run `react-native run-android` with metro bundler. The app opens with an error.
2. Open DevSettings > Dev Settings > Disable Use JS Deltas
3. `npm run haul start --platform android`
4. `cd android && ./gradlew app:assembleDebug && ./gradlew installDebug

**Comment by zamotany** [comment]
This is no longer an issue on the [`next`](https://github.com/callstack/haul/tree/next) branch where we're doing a revamp of Haul. If you're using RN 0.59 or 0.60 go check it out - it's much more stable.

**Comment by zamotany** [comment]
If anyone is having this issue please use `@haul-bundler/cli` (if not already using) and feel free to open a new issue or reopen this one.
