### ISSUE TITLE
How do I set up Haul for android?

### ISSUE THREAD

**Issue by uber5001** [callstack/haul#532]
Every time I've tried setting up haul, using various versions of Haul and React Native, I always get an "Unknown" error, or some other error on the android emulator, but everything works fine with the metro bundler.

software | version
-- | --
Haul | 1.0.0-rc.13
react-native | 0.57.0
node | v11.14.0
npm or yarn | npm 6.9.0
windows | 10 education version 1803

Here's a typical setup experience for me, run from powershell:

 - `react-native init --version="react-native@0.57.0" haultest8`
   - If I do `react-native run-android` here, the project works fine on the emulator with metro
 - `cd haultest8`
 - `npm i -D haul` - installs rc13
 - `npx haul init`
   - "Adding haul script to your package.json" freezes, so I go to the init script in node modules and comment that out and rerun this
 - `npx haul start`
   - give a lot of warnings at startup about core-js, these are fixed in rc15.
 - (in a different powershell) `react-native run-android`
   - Error from haul and emulator: `ERROR ./node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/assertThisInitialized' in 'C:\Users\Scott\Desktop\haultest8\node_modules\react-native\Libraries\Animated\src'
resolve '@babel/runtime/helpers/assertThisInitialized' in 'C:\Users\Scott\Desktop\haultest8\node_modules\react-native\Libraries\Animated\src'`

Another attempt, but with haul@next (rc15) and latest react-native (0.59.4):

 - `react-native init haultest9` - installs react-native@0.59.4
 - `cd haultest9`
 - `npm i -D haul@next` - installs haul@1.0.0-rc.15
 - `npx haul init` - freezes like before, have to edit script and rerun
 - `npx haul start`
 - (in a different powershell) `react-native run-android`
 - error: `react-hot-loader` can't resolve `react-dom`
 - kill haul, `npm i react-dom` (16.8.6), `npx haul start`, reload in emulator
 - emulator stuck on loading. Notice that the request was for index.delta. Open dev settings, see that bundle deltas was never on. Close dev settings. reload in emulator.
 - Notice that emulator now requests /index.bundle instead, even though no settings were changed.
 - error in emulator, but not in haul: "Unknown". See image.

![AndroidEmu](https://user-images.githubusercontent.com/3348363/56097173-26d00c00-5eae-11e9-8ad4-38cec19bf574.PNG)

I'm not sure how to get past this "Unknown" error, and I don't know how to get more information about it. stdout.log is empty and stderr.log has the following:

```
(node:22580) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at AssetResolver.apply (C:\Users\Scott\Desktop\haultest9\node_modules\haul\src\resolvers\AssetResolver.js:41:10)
    at plugins.forEach.plugin (C:\Users\Scott\Desktop\haultest9\node_modules\enhanced-resolve\lib\ResolverFactory.js:276:10)
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (C:\Users\Scott\Desktop\haultest9\node_modules\enhanced-resolve\lib\ResolverFactory.js:275:10)
    at ResolverFactory._create (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\ResolverFactory.js:60:28)
    at ResolverFactory.get (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\ResolverFactory.js:52:28)
    at Compilation.buildModule (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\Compilation.js:638:25)
    at moduleFactory.create (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\Compilation.js:1021:12)
    at MultiModuleFactory.create (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\MultiModuleFactory.js:18:3)
    at semaphore.acquire (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\Compilation.js:968:18)
    at Semaphore.acquire (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\util\Semaphore.js:29:4)
    at Compilation._addModuleChain (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\Compilation.js:967:18)
    at Compilation.addEntry (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\Compilation.js:1074:8)
    at compiler.hooks.make.tapAsync (C:\Users\Scott\Desktop\haultest9\node_modules\webpack\lib\MultiEntryPlugin.js:53:17)
    at AsyncParallelHook.eval [as callAsync] (eval at create (C:\Users\Scott\Desktop\haultest9\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncParallelHook.lazyCompileHook (C:\Users\Scott\Desktop\haultest9\node_modules\tapable\lib\Hook.js:154:20)
```

How do I diagnose and get past this "Unknown" error and get haul working?

**Comment by swdenglian** [comment]
you can see #535

**Comment by uber5001** [comment]
Closing this. It looks like this is a duplicate of #535
