### ISSUE TITLE
WebSocket connection error when trying to load bundle

### ISSUE THREAD

**Issue by EricPolman** [callstack/haul#630]
Hi, when I am running the packager and try to load via either a simulator or a physical device, I get the error below. This started happening after I upgraded to @haul-bundler/cli instead of "haul" package. I am running windows with an android emulator. The error also occurs when the debugger is attached, and also when I try to bundle with `--eager android`.

How can I get this to work or figure out what is going wrong?

````
done ▶︎ Packager server running on http://localhost:8081
info ▶︎ Compiling bundle "index" for platform android
done ▶︎ Successfully run: adb reverse tcp:8081 tcp:8081
error ▶︎ events.js:174
      throw er; // Unhandled 'error' e
error ▶︎ vent


Error: connect UNKNOWN //pipe/tmp/HAUL_SOCKET_43401_.socket
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at ClientRequest.req.on (C;\path\to\project\packages\react-native-app\node_modules\@haul-bundler\core-legacy\node_modules\ws\lib\websocket.js:568:15)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback **(internal/process/next_tick.js:63:19)`**
```

**Comment by zamotany** [comment]
@EricPolman I'm not sure why the error is happening since the code related to it wasn't changed. That being said, I do plan to refactor some of the logic related to that and try to make it more robust.

**Comment by Karpengold** [comment]
Hi @zamotany. Is here any updates for this issue? I got same on windows after react-native run-android command:

```
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
Emitted 'error' event at:
at ClientRequest.<anonymous> (C:\Users\karps\AndroidStudioProjects\reactNativeDhtmlxScheduler\template\node_modules\@haul-bundler\core-legacy\node_modules\ws\lib\websocket.js:568:15)
at ClientRequest.emit (events.js:203:13)
at Socket.socketErrorListener (_http_client.js:402:9)
at Socket.emit (events.js:203:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at processTicksAndRejections (internal/process/task_queues.js:77:11) {
errno: 'UNKNOWN',
code: 'UNKNOWN',
syscall: 'connect',
address: '//pipe/tmp/HAUL_SOCKET_130289_.socket'
}
```
```
"@haul-bundler/babel-preset-react-native": "^0.13.0",
 "@haul-bundler/cli": "^0.13.0",
 "@haul-bundler/preset-0.60": "^0.13.0",
```

**Comment by zamotany** [comment]
@Karpengold Well the issue is only reproducible on Windows, so if someone with Windows machine can take a shot at fixing it and sending a PR, that would be awesome (I can help and provide some context if needed). Otherwise, I'll fix it myself, but no ETA.
