### ISSUE TITLE
After haul upgrade can't compile with TypeError: compilation.getAsset is not a function

### ISSUE THREAD

**Issue by TNorth22** [callstack/haul#652]
## Environment

```
    "@haul-bundler/babel-preset-react-native": "^0.13.2",
    "@haul-bundler/cli": "^0.13.1",
    "@haul-bundler/inspector": "^0.13.0",
    "@haul-bundler/preset-0.60": "^0.13.0",
    "react-native": "^0.61.1",
     Node v10.16.0
```

Config:

```
// since preset-0.61 isn't yet available
import { withPolyfills, makeConfig } from '@haul-bundler/preset-0.60';

const removeRuleByTest = (moduleConfig, test) => {
  const index = moduleConfig.findIndex(rule => {
    if (rule.test) {
      return rule.test.toString() === test.toString();
    }
    return false;
  });
  moduleConfig.splice(index, 1);
};

export default makeConfig({
  bundles: {
    index: platform => ({
      entry: withPolyfills(`./src/index.${platform}.js`),
      transform({ config }) {
        // Remove babel-loader, as it handles both .ts(x) and .js(x) files
        removeRuleByTest(config.module.rules, /\.[jt]sx?$/);

        config.module.rules = [
          {
            exclude: /node_modules(?!.*[\/\\](react|@react-native-community|@haul-bundler))/,
            test: /\.tsx?$/,
            loader: 'ts-loader',
          },
          ...config.module.rules,

          // Re-add the babel-loader, now only for .js(x)
          {
            exclude: /node_modules(?!.*[\/\\](react|@react-native-community|@haul-bundler))/,
            test: /\.jsx?$/,
            loader: require.resolve('babel-loader'),
            options: {
              plugins: [require.resolve('@haul-bundler/core/build/utils/fixRequireIssues')],
            },
          },
          ...config.module.rules,
        ];

        config.resolve.extensions = [
          `.${platform}.ts`,
          '.mobile.ts',
          '.native.ts',
          `.${platform}.tsx`,
          '.mobile.tsx',
          '.native.tsx',
          '.ts',
          '.tsx',
          ...config.resolve.extensions,
        ];
      },
    }),
  },
});
```

## Description

After upgrading to the new haul bundle from a working legacy instance and starting with a fresh config I seemingly can't exclude things from Typescript checks and compilation terminates.  Not sure what I'm missing or am I looking at an outdated config?

```
Traviss-MacBook-Pro:xc **$ yarn ios --haul-inspector
yarn run v1.16.0
$ NODE_OPTIONS=--max_old_space_size=8192 REACT_NATIVE=true NODE_ENV=development yarn haul start --platform ios --eager ios --haul-inspector
[Logs]

done ▶︎ Packager server running on http://localhost:8081
error ▶︎ /Users/**/**/xc/node_modules/@haul-bundler/core/node_modules/webpack/lib/SourceMapDevToolPlugin.js:179
const asset = compilation.getAsset(file).source;


TypeError: compilation.getAsset is not a function
at files.forEach (/Users/**/**/xc/node_modules/@haul-bundler/core/node_modules/webpack/lib/SourceMapDevToolPlugin.js:179:33)
at Array.forEach (<anonymous>)
at compilation.hooks.afterOptimizeChunkAssets.tap (/Users/**/**/xc/node_modules/@haul-bundler/core/node_modules/webpack/lib/SourceMapDevToolPlugin.js:178:12)
at SyncHook.eval [as call] (eval at create (/Users/**/**/xc/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
at SyncHook.lazyCompileHook (/Users/**/**/xc/node_modules/tapable/lib/Hook.js:154:20)
at hooks.optimizeChunkAssets.callAsync.err (/Users/**/**/xc/node_modules/webpack/lib/Compilation.js:1313:42)
at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/**/**/xc/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
at AsyncSeriesHook.lazyCompileHook (/Users/**/**/xc/node_modules/tapable/lib/Hook.js:154:20)
at hooks.additionalAssets.callAsync.err (/Users/**/**/xc/node_modules/webpack/lib/Compilation.js:1309:36)
at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/**/**/xc/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
at AsyncSeriesHook.lazyCompileHook (/Users/**/**/xc/node_modules/tapable/lib/Hook.js:154:20)
at hooks.optimizeTree.callAsync.err (/Users/**/**/xc/node_modules/webpack/lib/Compilation.js:1305:32)
at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/**/**/xc/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
at AsyncSeriesHook.lazyCompileHook (/Users/**/**/xc/node_modules/tapable/lib/Hook.js:154:20)
at Compilation.seal (/Users/**/**/xc/node_modules/webpack/lib/Compilation.js:1242:27)
at hooks.make.callAsync.err (/Users/**/**/xc/node_modules/webpack/lib/Compiler.js:546:17)
at _err0 (eval at create (/Users/**/**/xc/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
at _addModuleChain (/Users/**/**/xc/node_modules/webpack/lib/Compilation.js:1093:12)
at processModuleDependencies.err (/Users/**/**/xc/node_modules/webpack/lib/Compilation.js:1005:9)
at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by zamotany** [comment]
@TNorth22 I'll take a lot at this tomorrow. In the meantime, if it's possible for you, could you create a repro repository, which I could use for testing?

**Comment by zamotany** [comment]
@TNorth22 I cannot reproduce your issue. The config looks file apart from duplicated `...config.module.rules`. The stack trace is pointing to a Webpack plugin for creating source maps, so you can try adding `sourceMap: false` to bundle config just to check if that helps. Other than that, without a reproduction repo I cannot do much.

**Comment by TNorth22** [comment]
Hey @zamotany thanks for the response.  Just getting back from vacation today.  Unfortunately I couldn't repro on a fresh rn project :-/.  

`sourceMap: false` results in a slew of typescript errors so i don't think that's going to help. 

I'll see if I can dig a little deeper and get some more info in the meantime.

**Comment by zamotany** [comment]
@TNorth22 setting `sourceMap` to `false` should not have any effect on loaders (and typescript compilation), which makes me think that maybe the underlying problem is with `ts-loader`/`typescript`. 

1. Can you post those errors from typescript?
2. Did you tried `haul bundle` instead of `start`? Same results?

**Comment by zamotany** [comment]
@rebirthtobi Can you post your `haul.config.js`?

**Comment by rebirthtobi** [comment]
@zamotany this is it below
```import { withPolyfills, makeConfig } from "@haul-bundler/preset-0.60";
import path from 'path';
import TsconfigPathsPlugin from "tsconfig-paths-webpack-plugin";
import webpack from "webpack";
import childProcess from "child_process";
import ForkTsCheckerWebpackPlugin from "fork-ts-checker-webpack-plugin";
import { langFallbacks, langs, resolve } from "./webpack/util";
import DotenvJsonPlugin from "./webpack/webpack-dotenv-json-plugin";
import GettextPlugin from "./webpack/webpack-gettext-plugin";
import CacheLoaderPlugin from "./webpack/webpack-cache-loader-plugin";


const srcDirs = [resolve("src"), resolve("packages"), resolve("node_modules/@tobi"), resolve("storybook/stories")];
const srcExts = [".tsx", ".ts", ".jsx", ".js"];


function prefixSrcExts(prefixes) {
  const extensions = [];

  prefixes.forEach(prefix => {
    const prefixed = srcExts.map(ext => `${prefix}${ext}`);
    extensions.push(...prefixed);
  });

  return extensions;
}

export default makeConfig({
  bundles: {
    index: ({ platform, dev }) => {
      const entry = dev ? "dev" : "index";
      return {
        entry: withPolyfills(`src/native/${entry}`),
        transform({ config }) {
          config.resolve.alias = {
            ...config.resolve.alias,
            "@storybook/react": path.join(__dirname, "@storybook/react-native"),
            "~": path.join(__dirname, "src"),
          };
          config.resolve.extensions = prefixSrcExts([`.${platform}`, ".native", ""]);
          config.resolve.plugins.push(new TsconfigPathsPlugin());
          config.output.chunkFilename = "[name]";
          config.resolveLoader = {
            alias: {
              "svg-inline-loader": require.resolve("./webpack/svg-ext-to-png-loader"),
            },
          };

          config.module.noParse = /google-libphonenumber/;

          config.module.rules = [
            ...config.module.rules,

            {
              test: /\.svg$/,
              use: {
                loader: require.resolve("./webpack/svg-ext-to-png-loader"),
              },
            },

            {
              test: /\.worker\.[tj]s$/,
              include: srcDirs,
              use: {
                loader: require.resolve("./webpack/error-loader"),
                options: {
                  text: "Imported web worker in native build",
                },
              },
            },

            {
              test: /\.tsx?$/,
              include: srcDirs,
              use: [
                {
                  loader: "ts-loader",
                  options: {
                    logLevel: "warn",
                    transpileOnly: true,

                    compilerOptions: {
                      sourceMap: true,
                      importHelpers: true,
                      noEmit: false,
                    },
                  },
                },
              ]
            },

            {
              test: /\.scss$/,
              use: {
                loader: require.resolve("./webpack/empty-loader"),
              },
            },
          ];

          config.plugins.push(
              new webpack.EnvironmentPlugin({
                NATIVE: true,
                DEBUG: dev,
                APP_VERSION: "webpack",
                BUILD_ID: childProcess
                    .execSync("git rev-parse HEAD")
                    .toString()
                    .trim(),
                LANGUAGE: langs[0],
              }),

              new DotenvJsonPlugin({
                path: resolve(".env"),
              }),

              new GettextPlugin({
                dir: resolve("loc"),
                langs,
                ext: ".loc",
                emitEntrypoints: false,
                fallbacks: langFallbacks,
              }),

              new ForkTsCheckerWebpackPlugin({
                checkSyntacticErrors: true,
              }),
          );

          if (dev) {
            config.plugins.push(new CacheLoaderPlugin());
          }

        },
      }
    }
  },
});
```

**Comment by zamotany** [comment]
@TNorth22 @rebirthtobi  Can you add `"resolution": { "webpack": "4.39.1" }`, do `yarn install` and check if the error is still happening? Can you also try with `"resolution": { "webpack": "4.41.1" }`?

**Comment by rebirthtobi** [comment]
@zamotany i believe that fixes it but i'm faced with a new error 
`.babelrcRoots is not allowed in .babelrc or "extends"ed files, only in root programmatic options, or babel.config.js/config`

pointing to `@haul-bundler/preset-0.60/node_mudules/babel-loader/lib/index.js`

**Comment by zamotany** [comment]
@rebirthtobi Can you post your Babel config file??

**Comment by rebirthtobi** [comment]
```
const isTest = process.env.NODE_ENV === "test";

const modules = isTest || process.env.REACT_NATIVE ? "commonjs" : false;
const targets = process.env.REACT_NATIVE ? { node: "current" } : undefined;

const plugins = [
    "@babel/plugin-transform-runtime",
    // https://babeljs.io/docs/en/babel-plugin-proposal-decorators#note-compatibility-with-babel-plugin-proposal-class-properties
    ["@babel/plugin-proposal-decorators", { legacy: true }],
    "@babel/plugin-proposal-nullish-coalescing-operator", // react native support
];

// @babel/plugin-proposal-class-properties has a bug in react native around it's use of flow
// It's only used for test mocks, so we can live without it.
// https://github.com/facebook/react-native/issues/21154
if (isTest) {
    plugins.push(["@babel/plugin-proposal-class-properties", { loose: true }]);
}

module.exports = {
    babelrcRoots: ["./tasks", "./storybook", "./webpack"],
    presets: [
        [
            "@babel/preset-env",
            {
                modules,
                targets,
            },
        ],
        "@babel/preset-react",
        "@babel/preset-flow", // used by react-native in tests
    ],
    plugins,
};
```

**Comment by hjhart** [comment]
Just as a note – taking the note from @zamotany above worked for us. There was a small typo, however, and it is:

```
"resolutions": { "webpack": "4.41.1" }
```

Noting that the key recommended above was `resolution` but should be `resolutions`.

Thanks!

**Comment by zamotany** [comment]
Ok, so this issue looks like it's caused by duplicated `webpack` depednency. I need a volunteer to:
1. Remove `resolutions` from `package.json`
2. `yarn install`
3. `yarn list --pattern webpack`
4. Paste the outout

@hjhart @TNorth22 @rebirthtobi

**Comment by zamotany** [comment]
@rebirthtobi I believe the issue with `.babelrcRoots` is connected with your Babel config. In haul we don't use/specify `babelrcRoots`.

**Comment by hjhart** [comment]
@zamotany 
```
yarn list v1.15.2
├─ @haul-bundler/basic-bundle-webpack-plugin@0.13.0
├─ @haul-bundler/core@0.13.2
│  └─ webpack@4.41.2
├─ @haul-bundler/ram-bundle-webpack-plugin@0.13.0
├─ @rails/webpacker@4.0.7
│  ├─ webpack-cli@3.3.9
│  └─ webpack@4.41.2
├─ @storybook/core@3.4.11
│  ├─ uglifyjs-webpack-plugin@0.4.6
│  ├─ webpack-dev-middleware@1.12.2
│  └─ webpack@3.12.0
├─ @storybook/react@3.4.11
│  └─ webpack@3.12.0
│     └─ uglifyjs-webpack-plugin@0.4.6
├─ case-sensitive-paths-webpack-plugin@2.2.0
├─ compression-webpack-plugin@2.0.0
├─ dotenv-webpack@1.5.7
├─ html-webpack-plugin@2.30.1
├─ last-call-webpack-plugin@3.0.0
├─ optimize-css-assets-webpack-plugin@5.0.3
├─ pnp-webpack-plugin@1.5.0
├─ simple-progress-webpack-plugin@1.1.2
├─ terser-webpack-plugin@1.4.1
├─ uglifyjs-webpack-plugin@1.3.0
├─ voom@0.0.1
│  └─ webpack-cli@3.3.9
├─ webpack-assets-manifest@3.1.1
├─ webpack-cli@3.1.2
├─ webpack-dev-middleware@3.4.0
├─ webpack-dev-server@3.1.9
├─ webpack-hot-middleware@2.24.3
├─ webpack-log@2.0.0
├─ webpack-sources@1.4.3
└─ webpack@4.21.0
✨  Done in 2.10s.
```

**Comment by EugenePisotsky** [comment]
any updates? I have the same issue

**Comment by zamotany** [comment]
@EugenePisotsky There's no update. I cannot reproduce the issue. It seams it's connected with specific `haul.config.js` and/or duplicated `webpack` dependency, but without any repro I cannot do much. If you want to have this issue resolved, please try to create a repro project and post the link to it here.

**Comment by DaveWelling** [comment]
Future googlers - FWIW - I had this error and was able to resolve it by uninstalling webpack and webpack-cli, then installing the latest version of those two.

**Comment by denieler** [comment]
This issue was solved for me by upgrading webpack from 4.33 to 4.46 version. It looks like `getAssets` feature was added only in webpack version `4.40`.
